### ISSUE TITLE
What to do in case Styleguide using RGBa ?

### ISSUE THREAD

**Issue by jitendravyas** [himynameisdave/postcss-rgb-plz#6]

**Comment by himynameisdave** [comment]
Right so currently this is not supported, but perhaps we could add an option for RGBa vals...

**Comment by himynameisdave** [comment]
@jitendravyas In the meantime I recommend that you try adding this [`postcss-rgb-to-rgba`](https://github.com/vital-software/postcss-rgb-to-rgba) plugin to your PostCSS pipeline after `postcss-rgb-plz` if that is what you are after 👍 

Closing because I don't think we are going to support RGBa values in this plugin, given that there are already other plugins that do this, and as the PostCSS plugin guidelines say, the aim is to [do one thing and do it well](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#12-do-one-thing-and-do-it-well).
